# Use root/example as user/password credentials
version: '3.1'

services:

  code:
    build: .
    container_name: slimCMS
    volumes: 
      - ./:/var/www
      - ./public:/var/www/html
    ports:
      - 5000:80
    depends_on: 
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: slimcms

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080